# Generated by Django 4.0.5 on 2022-11-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_doc',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
