# Generated by Django 4.0.5 on 2022-11-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_add_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_doc',
            name='password',
        ),
        migrations.RemoveField(
            model_name='add_doc',
            name='username',
        ),
    ]
