# Generated by Django 4.0.5 on 2022-11-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_add_admin_rename_name_add_doc_doctorname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_doc',
            name='deprmt',
        ),
        migrations.AddField(
            model_name='add_doc',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.department'),
        ),
    ]
