# Generated by Django 4.0.5 on 2022-12-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0009_alter_add_doc_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_doc',
            name='image',
            field=models.ImageField(null=True, upload_to='abcdhospital/index/static/images'),
        ),
    ]
