# Generated by Django 4.0.5 on 2022-11-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='userName',
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
