# Generated by Django 4.0.5 on 2022-11-25 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_department'),
        ('index', '0003_book_appoinment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appoinment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.department'),
        ),
        migrations.AddField(
            model_name='book_appoinment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.register'),
        ),
    ]
