# Generated by Django 4.0.5 on 2022-11-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userName',
            field=models.CharField(max_length=100),
        ),
    ]
