# Generated by Django 4.0.5 on 2022-11-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='userName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
