# Generated by Django 4.0.5 on 2022-12-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_book_appoinment_booking_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_appoinment',
            old_name='user_id',
            new_name='user',
        ),
    ]
