# Generated by Django 4.0.5 on 2022-12-12 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0012_alter_add_doc_image'),
        ('index', '0018_rename_user_book_appoinment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.add_doc'),
        ),
    ]
