# Generated by Django 4.0.5 on 2022-12-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_account_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_appoinment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.account'),
        ),
    ]
