# Generated by Django 4.0.5 on 2022-12-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_alter_book_appoinment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appoinment',
            name='medicines',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='book_appoinment',
            name='prescription',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
