# Generated by Django 4.0.5 on 2022-12-07 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
                ('report', models.CharField(max_length=150)),
                ('medicine', models.CharField(max_length=100)),
            ],
        ),
    ]
